version: '3.0'
services:
    proxy:
        restart: always
        container_name: proxy
        image: nexus.scolvo.solutions:18088/scolvo/scolvo-dep-proxy:1.3.0
        environment:
        - KEYCLOAK_ADMIN_ALLOWED_IP=${KEYCLOAK_ADMIN_ALLOWED_IP:-0.0.0.0/0}
        - DEFAULT_REDIRECT_PATH=scolvo-webapp/
        ports:
        - '80:80'
        - '443:443'
        logging:
          options:
            max-size: "50m"
            max-file: "4"
    auth:
        restart: always
        container_name: auth
        image: nexus.scolvo.solutions:18088/scolvo/scolvo-dep-auth:2.2.0
        depends_on:
        - authdb
        ports:
        - '8080:8080'
        - '8443:8443'
        environment:
        - KEYCLOAK_USER=${KEYCLOAK_USER}
        - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
        - SU_PASSWORD=${SU_PASSWORD}
        - PROXY_ADDRESS_FORWARDING=true
        - DB_VENDOR=mariadb
        - JDBC_PARAMS='connectTimeout=30&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8'
        - DB_ADDR=authdb
        - DB_PORT=3306
        - DB_DATABASE=${AUTHDB_MYSQL_DATABASE:-keycloak}
        - DB_USER=${AUTHDB_MYSQL_USER}
        - DB_PASSWORD=${AUTHDB_MYSQL_PASSWORD}
        - SMTP_USER=${EMAIL_USERNAME}
        - SMTP_PASSWORD=${EMAIL_PASSWORD}
        - SMTP_FROM=${EMAIL_USERNAME}
        - SMTP_FROM_DISPLAY_NAME=${SMTP_FROM_DISPLAY_NAME:-Scolvo}
        - AUDIT_EVENTS_EXPIRATION_SECS=${AUDIT_EVENTS_EXPIRATION_SECS:-31536000}
        - REALM_DISPLAY_NAME=${REALM_DISPLAY_NAME:-Scolvo}
        - KEYCLOAK_FRONTEND_URL=${EXTERNAL_BASE_URL}/auth
        logging:
          options:
            max-size: "50m"
            max-file: "4"
    mq:
        restart: always
        container_name: mq
        image: nexus.scolvo.solutions:18088/scolvo/scolvo-dep-mq:1.1.0
        hostname: scolvomq
        ports:
        - '5671:5671'
        - '15672:15672'
        environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        volumes:
        - "mqdb:/var/lib/rabbitmq:Z"
        logging:
          options:
            max-size: "50m"
            max-file: "4"
    authdb:
        restart: always
        container_name: authdb
        image: nexus.scolvo.solutions:18088/scolvo/scolvo-dep-mariadb:1.1.0
        environment:
        - MYSQL_DATABASE=${AUTHDB_MYSQL_DATABASE:-keycloak}
        - MYSQL_USER=${AUTHDB_MYSQL_USER}
        - MYSQL_PASSWORD=${AUTHDB_MYSQL_PASSWORD}
        - MYSQL_PORT_3306_TCP_ADDR=${AUTHDB_MYSQL_PORT_3306_TCP_ADDR:-authdb}
        - MYSQL_PORT_3306_TCP_PORT=${AUTHDB_MYSQL_PORT_3306_TCP_PORT:-3306}
        - KEYCLOAK_USER=${AUTHDB_MYSQL_USER}
        - KEYCLOAK_PASSWORD=${AUTHDB_MYSQL_PASSWORD}
        - PROXY_ADDRESS_FORWARDING=${AUTHDB_PROXY_ADDRESS_FORWARDING:-true}
        - MYSQL_ROOT_PASSWORD=${AUTHDB_MYSQL_ROOT_PASSWORD}
        volumes:
        - "authdb:/var/lib/mysql:Z"
        logging:
          options:
            max-size: "50m"
            max-file: "4"
    be:
        restart: always
        container_name: backend
        image: nexus.scolvo.solutions:18088/scolvo/scolvo-backend:2.39.0
        environment:
        - SCOLVO_PROJECT_ROOT=/app
        - EMAIL_USERNAME=${EMAIL_USERNAME}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - RABBIT_MQ_HOST=mq
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        - FCM_CREDENTIALS_FILE_PATH=/app/credentials/fcm_credentials.json
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
        - AWS_SECRET_KEY=${AWS_SECRET_KEY}
        - AWS_BUCKET_NAME=${BUCKET_NAME}
        - AWS_REGION_NAME=${REGION_NAME}
        - BEDB_MYSQL_USER=${BEDB_MYSQL_USER}
        - BEDB_MYSQL_PASSWORD=${BEDB_MYSQL_PASSWORD}
        - ENV=${ENV}
        - SPRING_PROFILES_ACTIVE=${BACKEND_SPRING_PROFILES_ACTIVE}
        - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-en}
        - LICENCE_CONFIG_PATH=/app/assets/config/backend/licenceConfig.yaml
        volumes:
        - ./assets:/app/assets
        - ${FCM_CREDENTIALS_FILE_PATH:-/dev/null}:/app/credentials/fcm_credentials.json
        - ${IMPORT_DIR_PATH:-./import}:/import
        depends_on:
        - auth
        - bedb
        - mq
        logging:
          options:
            max-size: "50m"
            max-file: "4"
    bedb:
        restart: always
        container_name: bedb
        image: nexus.scolvo.solutions:18088/scolvo/scolvo-dep-mariadb:1.1.0
        command: --character-set-server=utf8mb4
        environment:
        - MYSQL_USER=${BEDB_MYSQL_USER}
        - MYSQL_PASSWORD=${BEDB_MYSQL_PASSWORD}
        - MYSQL_PORT_3306_TCP_ADDR=${BEDB_MYSQL_PORT_3306_TCP_ADDR:-bedb}
        - MYSQL_PORT_3306_TCP_PORT=${BEDB_MYSQL_PORT_3306_TCP_PORT:-3306}
        - MYSQL_ROOT_PASSWORD=${BEDB_MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${BEDB_MYSQL_DATABASE:-bedb}
        - MYSQL_READONLY_USER=${BEDB_MYSQL_READONLY_USER:-}
        - MYSQL_READONLY_PASSWORD=${BEDB_MYSQL_READONLY_PASSWORD:-}
        ports:
        - '23306:3306'
        volumes:
        - "bedb:/var/lib/mysql:Z"
        logging:
          options:
            max-size: "50m"
            max-file: "4"
    admin:
        restart: always
        container_name: admin
        image: nexus.scolvo.solutions:18088/scolvo/scolvo-web-app:1.28.0
        environment:
        - MQ_URL=${MQ_URL:-mq}
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        - AUTH_URL=${AUTH_URL:-auth}
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
        - AWS_SECRET_KEY=${AWS_SECRET_KEY}
        - BUCKET_NAME=${BUCKET_NAME}
        - REGION_NAME=${REGION_NAME}
        - ENV=${ENV}
        - SPRING_PROFILES_ACTIVE=${ADMIN_SPRING_PROFILES_ACTIVE:-}
        - LIQUIBASE_CHANGELOG_FILE=file:/app/liquibase/changeLog.xml
        volumes:
        - ./assets/liquibase/mhub:/app/liquibase
        - ./assets/config/mhub/auth.jks:/app/auth.jks
        - ./assets/config/mhub/application.properties:/app/application.properties
        ports:
        - '29991:9991'
        - '${MHUB_SPRING_PORT:-28081}:8081'
        logging:
          options:
            max-size: "50m"
            max-file: "4"
    webapp:
        restart: always
        container_name: webapp
        image: nexus.scolvo.solutions:18088/scolvo/scolvo-web-app:1.28.0
        environment:
        - MQ_URL=${MQ_URL:-mq}
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        - AUTH_URL=${AUTH_URL:-auth}
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
        - AWS_SECRET_KEY=${AWS_SECRET_KEY}
        - BUCKET_NAME=${BUCKET_NAME}
        - REGION_NAME=${REGION_NAME}
        - ENV=${ENV}
        - SPRING_PROFILES_ACTIVE=${ADMIN_SPRING_PROFILES_ACTIVE:-}
        - LIQUIBASE_CHANGELOG_FILE=file:/app/liquibase/changeLog.xml
        volumes:
        - ./assets/liquibase/mhub:/app/liquibase
        - ./assets/config/webapp/auth.jks:/app/auth.jks
        - ./assets/config/webapp/application.properties:/app/application.properties
        ports:
        - '29992:9991'
        - '${MHUB_SPRING_PORT:-28082}:8081'
        logging:
          options:
            max-size: "50m"
            max-file: "4"


volumes:
    authdb:
    bedb:
    keycloak:
    mqdb:
