CREATE TABLE user (id TEXT NOT NULL, teamId TEXT, name TEXT NOT NULL, role TEXT NOT NULL, username TEXT NOT NULL, email TEXT NOT NULL, status TEXT, visible TEXT, CONSTRAINT USER_ID_PK PRIMARY KEY (id));
CREATE TABLE workplace (id TEXT NOT NULL, teamId TEXT, name TEXT NOT NULL, canBeBooked TEXT, CONSTRAINT PK_WORKPLACE PRIMARY KEY (id));
CREATE TABLE team (id TEXT NOT NULL, name TEXT NOT NULL, location TEXT NOT NULL, mapPicturePath TEXT, CONSTRAINT PK_TEAM PRIMARY KEY (id));
CREATE TABLE meetingRoom (id TEXT NOT NULL, name TEXT NOT NULL, capacity INTEGER NOT NULL, location TEXT NOT NULL, mapPicturePath TEXT, CONSTRAINT PK_MEETINGROOM PRIMARY KEY (id));
CREATE TABLE reservation (id TEXT NOT NULL, userId TEXT NOT NULL, workplaceId TEXT, meetingRoomId TEXT, start BIGINT NOT NULL, end BIGINT, numberOfParticipants INTEGER, CONSTRAINT PK_RESERVATION PRIMARY KEY (id));
